apiVersion: v1
kind: Service
metadata:
  name: coffee-website-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: coffee-website
